# For creating a plot of average value of <variable> at <locs>

locs:
  "Liepāja":
    lat: 56.511667
    lon: 21.013889

  "Alūksne":
    lat: 57.416667
    lon: 27.05

  "Dagda":
    lat: 56.083333
    lon: 27.533333

plot:
  variable: ssr
  xlabel: "Dienas stunda"
  ylabel: 'Saules izstarojums, $\frac{W}{m^2}$'
  linestyle: dashed
  legend_position: "upper right"
  fname: "task3_ssr_w_sqm"
  format: svg
